<!-- ICI IL Y AURA LES CATEGORIES DE PAINS EXEMPLE SANS GLUTEN ET EN PLUS BIO SA MERE -->


<section class="CategoryPastry">
    <article>
    <?php foreach($Categoriespastry as $Categorypastry) :?>
    <aside>
        <!-- je fais une boucle pour chercher les différentes catégories-->
        <div class="ModifArticle">

            <ul>
                <li class="Edit"><i class="fas fa-edit"></i></li>
                <li class="Delete"><a href="<?= $requestUrl ?>/modifallcategoryandproduct/deletecategorypastry?id=<?= $Categorypastry["id"]?>"><i class="fas fa-times"></i></a></li>
            </ul>


        </div>

        <div>

            <a  href="<?= $requestUrl."/categoryproductpastry?id=".$Categorypastry["id"]?>"><div class="divimgPastry"><img src="<?= $Categorypastry["photo"]?>" alt="imagekelkonk"></div>
                <div class="divNameOfCategoryPastry"><?= $Categorypastry["categorypastry"]?></div>
        </a>

        </div>
    </aside>
    <?php endforeach; ?>

    </article>
</section>
