

<div class="Corp">
<section>
    <article class="ArticleConcept">

        <h1>Concept de la boulangerie bio</h1>

        <p>Le concept est simple vous avez du pain, des sandwich et même des pâtisseries , a un prix raisonnable et surtout BIO.</p>
        <p>Vous êtes Chef d'entreprise, une start-up ou même particulier? Venez commander sur notre site, vous aurez le droit alors à une livraison au alentour de 10 kilomètre( de 1 a 3 euros suivant la distance) ou vous pouvez venir aussi chercher en boutique, une carte de fidélité sur le net et très prochainement vous allez pouvoir faire des sandwich personnalisé.</p>


    </article>
    <article class="ArticleProductBuy">
        <h1>Voici nos produits les plus achetés.</h1>

        <div class="grid-3">
        <aside class="aside1">
            <h1>Les Pains</h1>
        </aside>
        <aside class="aside2">
            <h1>Les Pâtisseries</h1>
        </aside>
        <aside class="aside3">
            <h1>Les Sandwich</h1>

        </aside>
        </div>
    </article>
    <article class="ArticlePartener">
        <!--<h1>Nos partenaires</h1>
        <p>Eric le pro de la farine</p>
        <p>Jean-claude le pro de la graine</p>
        <p>Chien qui ramène ça marde etc..</p>-->
    </article>
</div>

    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2629.2011119856847!2d2.4681293160229463!3d48.77805067927968!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e60ca18738e5f3%3A0x3042ba8466acd739!2s4+Place+de+l&#39;Abbaye%2C+94000+Cr%C3%A9teil!5e0!3m2!1sfr!2sfr!4v1546271251787" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
</section>
