<section class="CategoryProduct">

    <h1>Voici les produits de la catégorie <?= $TitlesBread["categoryproduct"] ?></h1>

<!--  Allproductbread  /-->


    <?php foreach($Allproductbread as $ProductBread): ?>
        <div class="Product grid-4">


            <div class="ImageProduct">
                <img src="<?= $wwwUrl."/images/image_site/".$ProductBread["photo"]?>" alt="y'apa">

            </div>
            <div class="InformationProduct">

                <p><?= $ProductBread["name"]?></p>
                <p><?= $ProductBread["description"]?></p>
            </div>
            <div class="InformationQuantityPrice">
                <p>Quantité restante : <?= $ProductBread["quantityinstock"] ?></p>
                <p>Prix : <?= $ProductBread["saleprice"] ?></p>

                <p>Quantité a commander: <input  class="quantity<?=$ProductBread["id_product"]?>" type="number" value="1" min="1" max="10"></p>
                <div class="Error" id="Error<?=$ProductBread["id_product"]?>"></div>

            </div>
            <div class="ButtonAddBasket">
                <p>Ajouter au panier</p>
                <span  class="AjoutBasket" data-id_product="<?=$ProductBread["id_product"]?>"><i class="fas fa-cart-arrow-down"></i></span>
            </div>


        </div>



    <?php endforeach; ?>

</section>