<section class="Signup">


    <div class="DivForm">
        <div class="DivSignup">


        <div>
            <h1>Inscription</h1>
        </div>

            <div>

                <p> Veuillez remplir ces champs.</p>

        </div>
    <form  method="post">


        <ul>


            <li>Votre Nom:</li>
            <li><input type="text" class="lastname"  name="lastname" maxlength="100"></li>
            <li>Votre Prénom:</li>
            <li><input type="text" class="firstname" name="firstname" maxlength="100"></li>
            <li>Votre E-mail:</li>
            <li><input type="text" class="email" name="email" maxlength="150"></li>
            <li>Votre Identifiant:</li>
            <li><div class="ErrorUser"></div><input type="text" class="user" name="user" maxlength="16"></li>
            <li>Votre Mot-de-passe:</li>
            <li><input type="password" class="passwordSignup" name="passwordSignup"></li>
            <li><input class="SendSignup" type="button" value="Envoyer"></li>

        </ul>



    </form>

    </div>

</section>